title: Happy Coding!

author:
  name: Mirnes Hasanovic
  url: https://github.com/mirneshasanovic/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 10

tags_path: /tags/
categories_path: /categories/
